### ISSUE TITLE
In "Become an Artist" form, hint text is not cleared in Chrome auto-fill

### ISSUE THREAD

**Issue by Norc** [adventurelibrary/ADVL-Issues#10]
Typing a response in a field clears out the hint text, but this does not happen during chrome autofill:

![image](https://user-images.githubusercontent.com/64667579/125018941-061e9e80-e044-11eb-94d1-0b78d49e22a9.png)

**Comment by zeel01** [comment]
We can't really fix Google forms, but this is temporary anyway.
