### ISSUE TITLE
Request to /users results in a Cognito error

### ISSUE THREAD

**Issue by Vindexus** [adventurelibrary/ADVL-Issues#7]
After I tried to log in as `test-user-01`

This was on testing.adventurelibrary.art

This is the result from the request to https://staging.adventurelibrary.art/users

```
error: {message: "Error: Cannot use a pool after calling end on the pool", details: "{}"}
details: "{}"
message: "Error: Cannot use a pool after calling end on the pool"
```

**Comment by zeel01** [comment]
Resolves https://github.com/adventurelibrary/ADVL-Issues/issues/6 (probably)
